config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups
  resources :teams
  resources :scouts

  root 'welcome#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :teams
  has_one :scout
  accepts_nested_attributes_for :scout

  def scout_attributes=(attribs)
    self.scout = Scout.find(attribs[:id])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :find_all_scouts

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: t('notice_created', obj: t('label', scope: 'activerecord.attributes.group'), name: params[:group][:name]) }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: t('notice_updated', obj: t('label', scope: 'activerecord.attributes.group'), name: @group.name) }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: t('notice_deleted', obj: t('label', scope: 'activerecord.attributes.group'), name: @group.name) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :location, :scout_attributes => [:id])
    end

    def find_all_scouts
      @scouts = Scout.all.order('lastname desc')
    end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group , html: {class: "form-horizontal"}) do |f| %>

  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, t('error')) %> <%= t('error_text') %></h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "control-label col-sm-3 col-md-3" %>
    <div class="col-sm-7 col-md-7">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :location, class: "control-label col-sm-3 col-md-3" %>
    <div class="col-sm-7 col-md-7">
      <%= f.text_field :location, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label t('manager', scope: 'activerecord.attributes.group'), class: "control-label col-sm-3 col-md-3" %>

    <div class="col-sm-7 col-md-7">
      <%= f.fields_for :scout , (@group.build_scout unless @group.scout), include_id: false do |b| %>
        <%= b.collection_select :id, @scouts, :id, :full_name , {include_blank: true}, {required: true, class: "form-control"} %>
      <% end %>
    </div>
  </div>

  <% unless current_page?(action: 'new') %>
    <div class="form-group">
      <%= f.label t('teams', scope: 'activerecord.attributes.group'), class: "control-label col-sm-3 col-md-3" %>
      <div class="col-sm-7 col-md-7">
        <%= render 'teams' %>
      </div>
    </div>

  <% end %>

  <div class="form-group">
    <div class="col-sm-12 col-md-12">
      <div class="btn-group pull-right">
        <%= link_to t('back'), groups_path, class: "btn btn-primary" %>
        <%= f.submit t('submit'), class: "btn btn-primary"  %>
      </div>
    </div>
  </div>

<% end %>

app/views/groups/_teams.html.erb
<ul class="list-group">
  <% @group.teams.each do |team| %>
    <li class="list-group-item"><%= team.name %></li>
    <%#= link_to team.name, team_path(team), class: "btn btn-link" %>
  <% end %>
</ul>

app/views/groups/edit.html.erb
<div class="jumbotron">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3><%= t('.title') %></h3>
    </div>

    <div class="panel-body">
      <%= render 'form' %>
    </div>

  </div>
</div>

app/views/groups/index.html.erb
<div class="jumbotron">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3><%= t('.title') %>
        <%= link_to t('.add'), new_group_path, class: "btn btn-success pull-right" %>
      </h3>
    </div>

    <div class="panel-body">

      <table class='table table-striped'>
        <thead>
          <tr>
            <th><%= t('name', scope: 'activerecord.attributes.group') %></th>
            <th><%= t('location', scope: 'activerecord.attributes.group') %></th>
            <th><%= t('manager', scope: 'activerecord.attributes.group') %></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <td><%= group.name %></td>
              <td><%= group.location %></td>
              <td><%= group.scout.full_name if group.scout %></td>
              <td>
                <div class="btn-group pull-right">
                  <%= link_to t('show'), group, class: "btn btn-primary" %>
                  <%= link_to t('edit'), edit_group_path(group), class: "btn btn-primary" %>
                  <%= link_to t('destroy'), group, class: "btn btn-primary" , method: :delete, data: { confirm: t('confirm') } %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="jumbotron">
  <!-- <div class="col-sm-1 col-md-1"></div> -->
  <!-- <div class="col-sm-10 col-md-10"> -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3><%= t('.title') %></h3>
      </div>

      <div class="panel-body">
        <%= render 'form' %>
      </div>
    <!-- </div> -->
  </div>
</div>

app/views/groups/show.html.erb
<div class="jumbotron">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3><%= @group.name %></h3>
    </div>

    <div class="panel-body">

      <div class="row">
        <div class="col-sm-3 col-md-3">
          <strong><%= t('manager', scope: 'activerecord.attributes.group') %></strong>
        </div>
        <div class="col-sm-9 col-md-9">
          <%= @group.scout.firstname %> <%= @group.scout.lastname %>
          <%= link_to @group.scout.email, scout_path(@group.scout) if @group.scout %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-3 col-md-3">
          <strong><%= t('location', scope: 'activerecord.attributes.group') %></strong>
        </div>
        <div class="col-sm-9 col-md-9">
          <%= @group.location %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-3 col-md-3">
          <strong><%= t('team_list') %></strong>
        </div>
        <div class="col-sm-9 col-md-9">
          <%= render 'teams' %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12 col-md-12">
          <div class="btn-group pull-right">
            <%= link_to t('edit'), edit_group_path(@group), class: "btn btn-primary" %>
            <%= link_to t('back'), groups_path, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>