config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups
  resources :teams
  resources :scouts

  root 'welcome#index'

end

app/models/scout.rb
class Scout < ActiveRecord::Base
  belongs_to :team
  # belongs_to :group

  validates :firstname, :lastname, :birth_date, presence: true
  validates :email, uniqueness: true, presence: true
  validates :code , uniqueness: true, presence: true

  def full_name
    firstname+" "+lastname
  end

  def age(dob)
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

end

app/controllers/scouts_controller.rb
class ScoutsController < ApplicationController
  before_action :set_scout, only: [:show, :edit, :update, :destroy]
  before_action :find_all_groups,  :find_all_teams
  # GET /scouts
  # GET /scouts.json
  def index
    @scouts = Scout.all
  end

  # GET /scouts/1
  # GET /scouts/1.json
  def show
  end

  # GET /scouts/new
  def new
    @scout = Scout.new
  end

  # GET /scouts/1/edit
  def edit
  end

  # POST /scouts
  # POST /scouts.json
  def create
    @scout = Scout.new(scout_params)

    respond_to do |format|
      if @scout.save
        format.html { redirect_to @scout, notice: t('notice_created', obj: t('label', scope: 'activerecord.attributes.scout'), name: params[:scout][:full_name]) }
        format.json { render :show, status: :created, location: @scout }
      else
        format.html { render :new }
        format.json { render json: @scout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scouts/1
  # PATCH/PUT /scouts/1.json
  def update
    respond_to do |format|
      if @scout.update(scout_params)
        format.html { redirect_to @scout, notice: t('notice_updated', obj: t('label', scope: 'activerecord.attributes.scout'), name: @scout.full_name) }
        format.json { render :show, status: :ok, location: @scout }
      else
        format.html { render :edit }
        format.json { render json: @scout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scouts/1
  # DELETE /scouts/1.json
  def destroy
    @scout.destroy
    respond_to do |format|
      format.html { redirect_to scouts_url, notice: t('notice_deleted', obj: t('label', scope: 'activerecord.attributes.scout'), name: @scout.full_name) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scout
      @scout = Scout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scout_params
      params.require(:scout).permit(:email, :firstname, :lastname, :address, :phonehome, :phonemobile, :birth_date, :level_id, :team_id, :group_id, :code, :notes, :school, :manager)
    end

    def find_all_groups
      @groups = Group.all.order('name desc')
    end

    def find_all_teams
      @teams = Team.all.order('name desc')
    end
end

app/helpers/scouts_helper.rb
module ScoutsHelper
end

app/views/scouts/_form.html.erb
<%= form_for(@scout , html: {class: "form-horizontal"}) do |f| %>

  <% if @scout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scout.errors.count, t('error')) %> <%= t('error_text') %></h2>

      <ul>
      <% @scout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :code , class: "control-label col-md-2"%>
    <div class="col-md-2">
      <%= f.text_field :code , required: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :firstname , class: "control-label col-md-2" %>
    <div class="col-md-4">
      <%= f.text_field :firstname, required: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :lastname , class: "control-label col-md-2" %>
    <div class="col-md-4">
      <%= f.text_field :lastname, required: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email , class: "control-label col-md-2" %>
    <div class="col-md-4">
      <%= f.text_field :email, required: true, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address , class: "control-label col-md-2" %>
    <div class="col-md-9">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :birth_date , class: "control-label col-md-2" %>
    <div class="col-md-2">
      <div class="input-group date" id="datepicker">
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
        </span>
        <% if @scout.birth_date %>
          <%= f.text_field :birth_date, :value => @scout.birth_date.strftime("%d/%m/%Y"), :class => 'form-control' %>
        <% else %>
          <%= f.text_field :birth_date, :class => 'form-control' %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :phonehome, class: "control-label col-md-2" %>
    <div class="col-md-2">
      <%= f.text_field :phonehome, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :phonemobile, class: "control-label col-md-2" %>
    <div class="col-md-2">
      <%= f.text_field :phonemobile, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label t('manager', scope: 'activerecord.attributes.scout'), class: "control-label col-md-2" %>
    <div class="col-md-1">
      <%= f.check_box :manager, class: "checkbox" %>
    </div>

    <div id="group" class="hidden">
      <!-- <div class="form-group"> -->
        <%= f.label t('label', scope: 'activerecord.attributes.group'), class: "control-label col-md-1" %>
        <div class="col-md-4">
          <%= f.collection_select :group_id, @groups, :id, :name , {include_blank: true}, class: "form-control" %>
        </div>
      <!-- </div> -->
    </div>

    <div id="team" class="hidden">
      <!-- <div class="form-group"> -->
        <%= f.label t('label', scope: 'activerecord.attributes.team'), class: "control-label col-md-1" %>
        <div class="col-md-4">
          <%= f.collection_select :team_id, @teams, :id, :name , {include_blank: true}, class: "form-control" %>
        </div>
      <!-- </div> -->
    </div>

  </div>

  <div class="form-group">
    <%= f.label :school , class: "control-label col-md-2" %>
    <div class="col-md-9">
      <%= f.text_area :school , cols: "80" , rows: "3", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :notes, class: "control-label col-md-2" %>
    <div class="col-md-9">
      <%= f.text_area :notes , cols: "80" , rows: "3", class: "form-control" %>
    </div>
  </div>


  <div class="form-group">
    <div class="col-md-12">
      <div class="btn-group pull-right">
        <%= link_to t('back'), scouts_path, class: "btn btn-primary" %>
        <%= f.submit t('submit'), class: "btn btn-primary"  %>
      </div>
    </div>
  </div>

<% end %>

<script>
$(document).ready(function() {

  // datepicker
  $('#datepicker').datepicker({
    format:    "dd/mm/yyyy",
    startDate: "01/01/1940",
    startView: 2,
    language:  "<%= I18n.locale.to_s %>",
    clearBtn:  true,
    autoclose: true
  })

  if ($('#scout_manager').is(':checked')) {
    $('#group').removeClass('hidden');
  } else {
    $('#team').removeClass('hidden');
  }

  $('#scout_manager').on('change', function() {
    var $checkbox = $(this);
    if ( $checkbox.prop('checked') ) {
      $('#group').removeClass('hidden');
      $('#team').addClass('hidden');
    } else {
      $('#team').removeClass('hidden');
      $('#group').addClass('hidden');
    }
  });
});

</script>

app/views/scouts/edit.html.erb
<div class="jumbotron">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3><%= t('.title') %></h3>
    </div>

    <div class="panel-body">
      <%= render 'form' %>
    </div>

  </div>
</div>

app/views/scouts/index.html.erb
<div class="jumbotron">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3><%= t('.title') %>
        <%= link_to t('.add'), new_scout_path, class: "btn btn-success pull-right" %>
      </h3>
    </div>

    <div class="panel-body">

      <table class='table table-striped'>
        <thead>
          <tr>
            <th><%= t('firstname', scope: 'activerecord.attributes.scout') %></th>
            <th><%= t('lastname', scope: 'activerecord.attributes.scout') %></th>
            <th><%= t('email', scope: 'activerecord.attributes.scout') %></th>
            <th><%= t('birth_date', scope: 'activerecord.attributes.scout') %></th>
            <th><%= t('name', scope: 'activerecord.attributes.team') %></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @scouts.each do |scout| %>
            <tr>
              <td><%= scout.firstname %></td>
              <td><%= scout.lastname %></td>
              <td><%= scout.email %></td>
              <td><%= scout.birth_date.strftime("%d/%m/%Y") %></td>
              <td><%= scout.team.name if scout.team %></td>
              <td>
                <div class="btn-group pull-right">
                  <%= link_to t('show'), scout, class: "btn btn-primary" %>
                  <%= link_to t('edit'), edit_scout_path(scout), class: "btn btn-primary" %>
                  <%= link_to t('destroy'), scout, class: "btn btn-primary" , method: :delete, data: { confirm: t('confirm') } %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/scouts/new.html.erb
<div class="jumbotron">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3><%= t('.title') %></h3>
    </div>

    <div class="panel-body">
      <%= render 'form' %>
    </div>

  </div>
</div>

app/views/scouts/show.html.erb
<div class="jumbotron">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3><%= @scout.firstname %> <%= @scout.lastname %> (<%= @scout.code %>)</h3>
    </div>

    <div class="panel-body">

      <div class="row">
        <div class="col-sm-3 col-md-3">
          <strong><%= t('email', scope: 'activerecord.attributes.scout') %></strong>
        </div>
        <div class="col-sm-9 col-md-9">
          <%= @scout.email %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-3 col-md-3">
          <strong><%= t('address', scope: 'activerecord.attributes.scout') %></strong>
        </div>
        <div class="col-sm-9 col-md-9">
          <%= @scout.address %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-3 col-md-3">
          <strong><%= t('phonehome', scope: 'activerecord.attributes.scout') %></strong>
        </div>
        <div class="col-sm-9 col-md-9">
          <%= @scout.phonehome %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-3 col-md-3">
          <strong><%= t('phonemobile', scope: 'activerecord.attributes.scout') %></strong>
        </div>
        <div class="col-sm-9 col-md-9">
          <%= @scout.phonemobile %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-3 col-md-3">
          <strong><%= t('age', scope: 'activerecord.attributes.scout') %></strong>
        </div>
        <div class="col-sm-9 col-md-9">
          <%= pluralize(@scout.age(@scout.birth_date), t('years_old')) %>
        </div>
      </div>

      <% if @scout.team %>
        <div class="row">
          <div class="col-sm-3 col-md-3">
            <strong><%= t('name', scope: 'activerecord.attributes.team') %></strong>
          </div>
          <div class="col-sm-9 col-md-9">
            <%= @scout.team.name %>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-3 col-md-3">
            <strong><%= t('name', scope: 'activerecord.attributes.group') %></strong>
          </div>
          <div class="col-sm-9 col-md-9">
            <%= @scout.team.group.name %>
          </div>
        </div>
      <% end %>

      <div class="row">
        <div class="col-sm-3 col-md-3">
          <strong><%= t('school', scope: 'activerecord.attributes.scout') %></strong>
        </div>
        <div class="col-sm-9 col-md-9">
          <%= @scout.school %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-3 col-md-3">
          <strong><%= t('notes', scope: 'activerecord.attributes.scout') %></strong><br>
        </div>
        <div class="col-sm-9 col-md-9">
          <%= @scout.notes %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12 col-md-12">
          <div class="btn-group pull-right">
            <%= link_to t('edit'), edit_scout_path(@scout), class: "btn btn-primary" %>
            <%= link_to t('back'), scouts_path, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>