config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups
  resources :teams
  resources :scouts

  root 'welcome#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  
  def after_sign_out_path_for(resource_or_scope)
    groups_path
  end

  def after_sign_in_path_for(resource_or_scope)
    groups_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    case flash_type
    when "sucess"
      "alert-success"
    when "error"
      "alert-danger"
    when "alert"
      "alert-warning"
    when "notice"
      "alert-info"
    else
      flash_type.to_s
    end
  end

end

app/views/application/_footer.html.erb
<footer class="footer">
  <div class='container'>
    <p>Copyright &copy Jérôme Tessier 2016</p>
  </div>
</footer>

app/views/application/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><%= link_to t("homepage"), root_path %></li>
        <li><%= link_to t("manage_groups"), groups_path %></li>
        <li><%= link_to t("manage_teams"), teams_path %></li>
        <li><%= link_to t("manage_scouts"), scouts_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to '<span><i class="glyphicon glyphicon-log-out"></i></span> '"#{t('logout')}".html_safe, destroy_user_session_path,
                          :method => :delete, :data => {:confirm => t('confirmation', :scope => 'devise.sessions')} %></li>
        <% else %>
          <li><%= link_to '<span><i class="glyphicon glyphicon-edit"></i></span> '"#{t('signup')}".html_safe, new_user_registration_path %></li>
          <li><%= link_to '<span><i class="glyphicon glyphicon-log-in"></i></span> '"#{t('login')}".html_safe, new_user_session_path %></li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>